## 1. Importar Librerias

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
import time
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

## 2. Nombre de usuario de Backloggd

In [19]:
usuario = "SilentStorm63"
url = f"https://www.backloggd.com/u/{usuario}/games"

## 3. Configuracion de Selenium (modo headless)

In [20]:
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

## 4. Iniciar Navegador

In [21]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
driver.get(url)
time.sleep(3)

## 5. Scroll para cargar más juegos (ajusta si tienes muchos)

In [ ]:
# for _ in range(15):
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#     time.sleep(1.5)

In [22]:
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)  # dar tiempo para que cargue
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

## 6. Extraer elementos

In [ ]:
# juegos = driver.find_elements(By.CSS_SELECTOR, ".game-text-centered")
# links = driver.find_elements(By.CSS_SELECTOR, ".cover-link")

In [23]:
juegos_encontrados = driver.find_elements(By.CSS_SELECTOR, ".game-cover")

## 7. Guardar info

In [ ]:
""" data = []
for juego, link in zip(juegos, links):
    nombre = juego.text.strip()
    href = link.get_attribute("href")
    data.append({
        "Juego": nombre,
        "URL": href
    })

driver.quit() """

In [ ]:
""" data = []

for game in games:
    try:
        name = game.find_element(By.CSS_SELECTOR, "img").get_attribute("alt")
        link = game.get_attribute("href")
        if name and link:
            data.append({
                "Juego": name,
                "URL": link
            })
    except Exception as e:
        print("Error con un juego:", e)

driver.quit() """

In [24]:
# Scrapeo de los juegos en la página

juegos = []

for juego in juegos_encontrados:
    try:
        link_element = juego.find_element(By.CSS_SELECTOR, ".cover-link")
        nombre_element = juego.find_element(By.CSS_SELECTOR, ".game-text-centered")

        url = "https://www.backloggd.com" + link_element.get_attribute("href")
        nombre = nombre_element.text.strip()

        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo un juego: {e}")

## Crear DataFrame

In [27]:
# Crear DataFrame
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos_completo.xlsx", index=False)
print(f"✅ Archivo generado con {len(df)} juegos")
df.head()

✅ Archivo generado con 40 juegos

  Juego                                                URL
0        https://www.backloggd.comhttps://backloggd.com...
1        https://www.backloggd.comhttps://backloggd.com...
2        https://www.backloggd.comhttps://backloggd.com...
3        https://www.backloggd.comhttps://backloggd.com...
4        https://www.backloggd.comhttps://backloggd.com...

In [26]:
df.head(5)

  Juego                                                URL
0        https://www.backloggd.comhttps://backloggd.com...
1        https://www.backloggd.comhttps://backloggd.com...
2        https://www.backloggd.comhttps://backloggd.com...
3        https://www.backloggd.comhttps://backloggd.com...
4        https://www.backloggd.comhttps://backloggd.com...

# Notas
__(23/04/2025)__
- Solo regresa el link de los juegos, no el nombre
- Solo obtengo 50 links

In [28]:
# --- 1. Librerías ---
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# --- 2. Configuración del navegador ---
options = Options()
options.add_argument("--start-maximized")  # Abrir maximizado
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- 3. Abrir Backloggd ---
usuario = "SilentStorm63"  # tu usuario
driver.get(f"https://www.backloggd.com/u/{usuario}/games/")

time.sleep(5)  # Esperar que cargue la página

# --- 4. Hacer scroll para cargar todos los juegos ---
scrolls = 30  # puedes ajustar este número si ves que aún no baja todo
for i in range(scrolls):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1.5)  # esperar a que carguen los nuevos juegos

print("✅ Scroll completo. Extrayendo datos...")

# --- 5. Extraer juegos ---
juegos = []

juegos_encontrados = driver.find_elements(By.CSS_SELECTOR, ".game-cover")

print(f"🎮 Juegos encontrados: {len(juegos_encontrados)}")

for juego in juegos_encontrados:
    try:
        link_element = juego.find_element(By.CSS_SELECTOR, ".cover-link")
        nombre_element = juego.find_element(By.CSS_SELECTOR, ".game-text-centered")

        url = "https://www.backloggd.com" + link_element.get_attribute("href")
        nombre = nombre_element.text.strip()

        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo un juego: {e}")

# --- 6. Guardar en Excel ---
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos.xlsx", index=False)

print(f"✅ Archivo generado con {len(juegos)} juegos.")

# --- 7. Cerrar navegador ---
driver.quit()

✅ Scroll completo. Extrayendo datos...
🎮 Juegos encontrados: 40
✅ Archivo generado con 40 juegos.

In [31]:
# --- 1. Librerías ---
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# --- 2. Configuración del navegador ---
options = Options()
options.add_argument("--start-maximized")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- 3. Abrir Backloggd ---
usuario = "SilentStorm63"  # tu usuario
pagina = 1
driver.get(f"https://www.backloggd.com/u/{usuario}/games/?page={pagina}")

time.sleep(5)  # Espera que cargue

# --- 4. Extraer juegos de esta página ---
juegos = []

# Ahora buscamos los bloques grandes de cada juego:
bloques_juegos = driver.find_elements(By.CSS_SELECTOR, "div.rating-hover")

print(f"🎮 Juegos encontrados en página {pagina}: {len(bloques_juegos)}")

for bloque in bloques_juegos:
    try:
        # dentro del bloque buscar el link y el nombre
        link_element = bloque.find_element(By.CSS_SELECTOR, "a.cover-link")
        nombre_element = bloque.find_element(By.CSS_SELECTOR, "div.game-text-centered")
        
        url_relativa = link_element.get_attribute("href")
        url = "https://www.backloggd.com" + url_relativa if url_relativa.startswith("/games") else url_relativa
        nombre = nombre_element.text.strip()
        
        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo datos de un juego: {e}")

# --- 5. Guardar en Excel ---
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos_pagina1.xlsx", index=False)

print(f"✅ Archivo generado con {len(juegos)} juegos.")

# --- 6. Cerrar navegador ---
driver.quit()

🎮 Juegos encontrados en página 1: 40
✅ Archivo generado con 40 juegos.

# Leer un juego

In [33]:
from bs4 import BeautifulSoup

# Cargar el archivo HTML
with open('backloggd.html', 'r', encoding='utf-8') as file:
    soup = BeautifulSoup(file, 'html.parser')

# Encontrar el primer juego
primer_bloque = soup.find('div', class_='rating-hover')

# Obtener URL
link_element = primer_bloque.find('a', class_='cover-link')
url_relativa = link_element.get('href')
url = "https://www.backloggd.com" + url_relativa

# Obtener Nombre
nombre_element = primer_bloque.find('div', class_='game-text-centered')
nombre = nombre_element.get_text(strip=True)

print("🎮 Nombre:", nombre)
print("🔗 URL:", url)

🎮 Nombre: Marvel Rivals
🔗 URL: https://www.backloggd.com/games/marvel-rivals/