## 1. Importar Librerias

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
import time
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

## 2. Nombre de usuario de Backloggd

In [19]:
usuario = "SilentStorm63"
url = f"https://www.backloggd.com/u/{usuario}/games"

## 3. Configuracion de Selenium (modo headless)

In [20]:
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

## 4. Iniciar Navegador

In [21]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
driver.get(url)
time.sleep(3)

## 5. Scroll para cargar más juegos (ajusta si tienes muchos)

In [ ]:
# for _ in range(15):
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#     time.sleep(1.5)

In [22]:
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)  # dar tiempo para que cargue
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

## 6. Extraer elementos

In [ ]:
# juegos = driver.find_elements(By.CSS_SELECTOR, ".game-text-centered")
# links = driver.find_elements(By.CSS_SELECTOR, ".cover-link")

In [23]:
juegos_encontrados = driver.find_elements(By.CSS_SELECTOR, ".game-cover")

## 7. Guardar info

In [ ]:
""" data = []
for juego, link in zip(juegos, links):
    nombre = juego.text.strip()
    href = link.get_attribute("href")
    data.append({
        "Juego": nombre,
        "URL": href
    })

driver.quit() """

In [ ]:
""" data = []

for game in games:
    try:
        name = game.find_element(By.CSS_SELECTOR, "img").get_attribute("alt")
        link = game.get_attribute("href")
        if name and link:
            data.append({
                "Juego": name,
                "URL": link
            })
    except Exception as e:
        print("Error con un juego:", e)

driver.quit() """

In [24]:
# Scrapeo de los juegos en la página

juegos = []

for juego in juegos_encontrados:
    try:
        link_element = juego.find_element(By.CSS_SELECTOR, ".cover-link")
        nombre_element = juego.find_element(By.CSS_SELECTOR, ".game-text-centered")

        url = "https://www.backloggd.com" + link_element.get_attribute("href")
        nombre = nombre_element.text.strip()

        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo un juego: {e}")

## Crear DataFrame

In [27]:
# Crear DataFrame
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos_completo.xlsx", index=False)
print(f"✅ Archivo generado con {len(df)} juegos")
df.head()

✅ Archivo generado con 40 juegos

  Juego                                                URL
0        https://www.backloggd.comhttps://backloggd.com...
1        https://www.backloggd.comhttps://backloggd.com...
2        https://www.backloggd.comhttps://backloggd.com...
3        https://www.backloggd.comhttps://backloggd.com...
4        https://www.backloggd.comhttps://backloggd.com...

In [26]:
df.head(5)

  Juego                                                URL
0        https://www.backloggd.comhttps://backloggd.com...
1        https://www.backloggd.comhttps://backloggd.com...
2        https://www.backloggd.comhttps://backloggd.com...
3        https://www.backloggd.comhttps://backloggd.com...
4        https://www.backloggd.comhttps://backloggd.com...

# Notas
__(23/04/2025)__
- Solo regresa el link de los juegos, no el nombre
- Solo obtengo 50 links

In [28]:
# --- 1. Librerías ---
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# --- 2. Configuración del navegador ---
options = Options()
options.add_argument("--start-maximized")  # Abrir maximizado
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- 3. Abrir Backloggd ---
usuario = "SilentStorm63"  # tu usuario
driver.get(f"https://www.backloggd.com/u/{usuario}/games/")

time.sleep(5)  # Esperar que cargue la página

# --- 4. Hacer scroll para cargar todos los juegos ---
scrolls = 30  # puedes ajustar este número si ves que aún no baja todo
for i in range(scrolls):
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1.5)  # esperar a que carguen los nuevos juegos

print("✅ Scroll completo. Extrayendo datos...")

# --- 5. Extraer juegos ---
juegos = []

juegos_encontrados = driver.find_elements(By.CSS_SELECTOR, ".game-cover")

print(f"🎮 Juegos encontrados: {len(juegos_encontrados)}")

for juego in juegos_encontrados:
    try:
        link_element = juego.find_element(By.CSS_SELECTOR, ".cover-link")
        nombre_element = juego.find_element(By.CSS_SELECTOR, ".game-text-centered")

        url = "https://www.backloggd.com" + link_element.get_attribute("href")
        nombre = nombre_element.text.strip()

        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo un juego: {e}")

# --- 6. Guardar en Excel ---
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos.xlsx", index=False)

print(f"✅ Archivo generado con {len(juegos)} juegos.")

# --- 7. Cerrar navegador ---
driver.quit()

✅ Scroll completo. Extrayendo datos...
🎮 Juegos encontrados: 40
✅ Archivo generado con 40 juegos.

In [31]:
# --- 1. Librerías ---
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# --- 2. Configuración del navegador ---
options = Options()
options.add_argument("--start-maximized")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- 3. Abrir Backloggd ---
usuario = "SilentStorm63"  # tu usuario
pagina = 1
driver.get(f"https://www.backloggd.com/u/{usuario}/games/?page={pagina}")

time.sleep(5)  # Espera que cargue

# --- 4. Extraer juegos de esta página ---
juegos = []

# Ahora buscamos los bloques grandes de cada juego:
bloques_juegos = driver.find_elements(By.CSS_SELECTOR, "div.rating-hover")

print(f"🎮 Juegos encontrados en página {pagina}: {len(bloques_juegos)}")

for bloque in bloques_juegos:
    try:
        # dentro del bloque buscar el link y el nombre
        link_element = bloque.find_element(By.CSS_SELECTOR, "a.cover-link")
        nombre_element = bloque.find_element(By.CSS_SELECTOR, "div.game-text-centered")
        
        url_relativa = link_element.get_attribute("href")
        url = "https://www.backloggd.com" + url_relativa if url_relativa.startswith("/games") else url_relativa
        nombre = nombre_element.text.strip()
        
        juegos.append({"Juego": nombre, "URL": url})
    except Exception as e:
        print(f"⚠️ Error extrayendo datos de un juego: {e}")

# --- 5. Guardar en Excel ---
df = pd.DataFrame(juegos)
df.to_excel("backloggd_juegos_pagina1.xlsx", index=False)

print(f"✅ Archivo generado con {len(juegos)} juegos.")

# --- 6. Cerrar navegador ---
driver.quit()

🎮 Juegos encontrados en página 1: 40
✅ Archivo generado con 40 juegos.

# Leer un juego

In [33]:
from bs4 import BeautifulSoup

# Cargar el archivo HTML
with open('backloggd.html', 'r', encoding='utf-8') as file:
    soup = BeautifulSoup(file, 'html.parser')

# Encontrar el primer juego
primer_bloque = soup.find('div', class_='rating-hover')

# Obtener URL
link_element = primer_bloque.find('a', class_='cover-link')
url_relativa = link_element.get('href')
url = "https://www.backloggd.com" + url_relativa

# Obtener Nombre
nombre_element = primer_bloque.find('div', class_='game-text-centered')
nombre = nombre_element.get_text(strip=True)

print("🎮 Nombre:", nombre)
print("🔗 URL:", url)

🎮 Nombre: Marvel Rivals
🔗 URL: https://www.backloggd.com/games/marvel-rivals/

# Pruebas

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time

# --- 1. Variables básicas ---
usuario = "SilentStorm63"
base_url = f"https://www.backloggd.com/u/{usuario}/games/?page="
pagina = 1

todos_los_juegos = []
urls_existentes = set()

headers = {
    "User-Agent": "Mozilla/5.0"
}

# --- 2. Loop para recorrer páginas ---
while True:
    print(f"Scrapeando página {pagina}...")
    
    url = base_url + str(pagina)
    response = requests.get(url, headers=headers)
    
    if response.status_code != 200:
        print(f"⚠️ Error al cargar página {pagina}. Código {response.status_code}")
        break
    
    soup = BeautifulSoup(response.content, 'html.parser')
    
    bloques_juegos = soup.find_all('div', class_='rating-hover')

    juegos_nuevos_encontrados = 0  # contador de juegos nuevos

    for bloque in bloques_juegos:
        try:
            link_element = bloque.find('a', class_='cover-link')
            nombre_element = bloque.find('div', class_='game-text-centered')

            if link_element and nombre_element:
                url_relativa = link_element.get('href')
                url_juego = "https://www.backloggd.com" + url_relativa
                nombre_juego = nombre_element.get_text(strip=True)

                if url_juego not in urls_existentes:  # 🚨 solo si es realmente nuevo
                    todos_los_juegos.append({
                        "Juego": nombre_juego,
                        "URL": url_juego
                    })
                    urls_existentes.add(url_juego)
                    juegos_nuevos_encontrados += 1
        except Exception as e:
            print(f"⚠️ Error leyendo un juego: {e}")

    if juegos_nuevos_encontrados == 0:
        print(f"✅ No se encontraron juegos nuevos en página {pagina}. Fin del scraping.")
        break

    pagina += 1
    time.sleep(1)

# --- 3. Guardar en Excel ---
df = pd.DataFrame(todos_los_juegos)
df.to_excel("backloggd_juegos_completo.xlsx", index=False)
df.head(5)

print(f"✅ ¡Scraping completo! Juegos encontrados: {len(df)}")

Scrapeando página 1...
Scrapeando página 2...
Scrapeando página 3...
Scrapeando página 4...
✅ No se encontraron juegos nuevos en página 4. Fin del scraping.
✅ ¡Scraping completo! Juegos encontrados: 91

In [2]:
df.head()

,Juego,URL
0,Marvel Rivals,https://www.backloggd.com/games/marvel-rivals/
1,Max: The Curse of Brotherhood,https://www.backloggd.com/games/max-the-curse-...
2,Destiny,https://www.backloggd.com/games/destiny/
3,Halo 5: Guardians,https://www.backloggd.com/games/halo-5-guardians/
4,Forza Motorsport 5,https://www.backloggd.com/games/forza-motorspo...

In [3]:
df.to_excel("backloggd_juegos_completo.xlsx", index=False, engine='openpyxl')

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# --- Mini prueba con 1 juego ---
data_prueba = [
    {"Juego": "Marvel Rivals", "URL": "https://www.backloggd.com/games/marvel-rivals/"}
]
df_prueba = pd.DataFrame(data_prueba)

# --- Configurar navegador ---
options = webdriver.ChromeOptions()
options.add_argument("--headless")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- Agregar columnas ---
df_prueba["Horas Jugadas"] = ""
df_prueba["Fecha Inicio"] = ""
df_prueba["Fecha Fin"] = ""

usuario = "SilentStorm63"

for index, row in df_prueba.iterrows():
    url_original = row['URL']
    slug = url_original.split("/games/")[-1].strip("/")
    log_url = f"https://backloggd.com/u/{usuario}/logs/{slug}/"

    print(f"🔍 Visitando: {log_url}")
    driver.get(log_url)
    time.sleep(3)

    # --- Buscar tiempo jugado ---
    try:
        # Buscar el <i> del reloj y luego subir al padre <p> para obtener el texto
        reloj_icono = driver.find_element(By.CLASS_NAME, "fa-stopwatch")
        tiempo_jugado = reloj_icono.find_element(By.XPATH, "./..").text.strip()
    except:
        tiempo_jugado = ""

    # --- Buscar fechas (last played y first played) ---
    try:
        texto_completo = driver.find_element(By.CLASS_NAME, "game-log-view").text
        lineas = texto_completo.split("\n")

        fecha_inicio = ""
        fecha_fin = ""
        for i, linea in enumerate(lineas):
            if "FIRST PLAYED" in linea.upper():
                fecha_inicio = lineas[i+1]
            if "LAST PLAYED" in linea.upper():
                fecha_fin = lineas[i+1]
    except:
        fecha_inicio = ""
        fecha_fin = ""

    # --- Guardar en el DataFrame ---
    df_prueba.at[index, "Horas Jugadas"] = tiempo_jugado
    df_prueba.at[index, "Fecha Inicio"] = fecha_inicio
    df_prueba.at[index, "Fecha Fin"] = fecha_fin

# Mostrar resultados
print("\n✅ Resultado:")
print(df_prueba)

# Cerrar navegador
driver.quit()

🔍 Visitando: https://backloggd.com/u/SilentStorm63/logs/marvel-rivals/

✅ Resultado:
           Juego                                             URL  \
0  Marvel Rivals  https://www.backloggd.com/games/marvel-rivals/

  Horas Jugadas       Fecha Inicio       Fecha Fin
0       49h 54m  December 12, 2024  April 14, 2025

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# --- CONFIGURACIÓN ---
EXCEL_ENTRADA = "backloggd_juegos_completo.xlsx"
EXCEL_SALIDA = "backloggd_juegos_con_logs.xlsx"
USUARIO = "SilentStorm63"

# --- Cargar Excel existente ---
df = pd.read_excel(EXCEL_ENTRADA)

# Añadir columnas si no existen
for col in ["Horas Jugadas", "Fecha Inicio", "Fecha Fin"]:
    if col not in df.columns:
        df[col] = ""

# --- Configurar navegador ---
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument('--ignore-certificate-errors')
options.add_argument('--allow-insecure-localhost')
options.add_argument('--disable-web-security')

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# --- Recorrer todos los juegos ---
for index, row in df.iterrows():
    url_original = row['URL']
    juego = row['Juego']
    
    slug = url_original.split("/games/")[-1].strip("/")
    log_url = f"https://backloggd.com/u/{USUARIO}/logs/{slug}/"

    print(f"🔍 {index+1}/{len(df)} - {juego}")
    print(f"    {log_url}")

    try:
        driver.get(log_url)
        time.sleep(2.5)

        # Horas jugadas
        try:
            reloj_icono = driver.find_element(By.CLASS_NAME, "fa-stopwatch")
            horas = reloj_icono.find_element(By.XPATH, "./..").text.strip()
        except:
            horas = ""

        # Fechas
        try:
            texto = driver.find_element(By.CLASS_NAME, "game-log-view").text
            lineas = texto.split("\n")

            fecha_inicio = ""
            fecha_fin = ""
            for i, linea in enumerate(lineas):
                if "FIRST PLAYED" in linea.upper():
                    fecha_inicio = lineas[i+1]
                if "LAST PLAYED" in linea.upper():
                    fecha_fin = lineas[i+1]
        except:
            fecha_inicio = ""
            fecha_fin = ""

        # Guardar en el DataFrame
        df.at[index, "Horas Jugadas"] = horas
        df.at[index, "Fecha Inicio"] = fecha_inicio
        df.at[index, "Fecha Fin"] = fecha_fin

    except Exception as e:
        print(f"⚠️ Error en {log_url}: {e}")

# --- Guardar nuevo Excel ---
df.to_excel(EXCEL_SALIDA, index=False)
print(f"\n✅ Archivo generado: {EXCEL_SALIDA} con {len(df)} juegos.")

# --- Cerrar navegador ---
driver.quit()

🔍 1/91 - Marvel Rivals
    https://backloggd.com/u/SilentStorm63/logs/marvel-rivals/
🔍 2/91 - Max: The Curse of Brotherhood
    https://backloggd.com/u/SilentStorm63/logs/max-the-curse-of-brotherhood/
🔍 3/91 - Destiny
    https://backloggd.com/u/SilentStorm63/logs/destiny/
🔍 4/91 - Halo 5: Guardians
    https://backloggd.com/u/SilentStorm63/logs/halo-5-guardians/
🔍 5/91 - Forza Motorsport 5
    https://backloggd.com/u/SilentStorm63/logs/forza-motorsport-5/
🔍 6/91 - Grounded
    https://backloggd.com/u/SilentStorm63/logs/grounded/
🔍 7/91 - Human: Fall Flat
    https://backloggd.com/u/SilentStorm63/logs/human-fall-flat/
🔍 8/91 - Dead by Daylight
    https://backloggd.com/u/SilentStorm63/logs/dead-by-daylight/
🔍 9/91 - Phogs!
    https://backloggd.com/u/SilentStorm63/logs/phogs/
🔍 10/91 - Halo Infinite
    https://backloggd.com/u/SilentStorm63/logs/halo-infinite/
🔍 11/91 - Spelunky 2
    https://backloggd.com/u/SilentStorm63/logs/spelunky-2/
🔍 12/91 - The Last of Us: Left Behind - Remastered
    https://backloggd.com/u/SilentStorm63/logs/the-last-of-us-left-behind-remastered/
🔍 13/91 - The Last of Us Part I
    https://backloggd.com/u/SilentStorm63/logs/the-last-of-us-part-i/
🔍 14/91 - Fall Guys
    https://backloggd.com/u/SilentStorm63/logs/fall-guys/
🔍 15/91 - Stories Untold
    https://backloggd.com/u/SilentStorm63/logs/stories-untold/
🔍 16/91 - Fortnite
    https://backloggd.com/u/SilentStorm63/logs/fortnite/
🔍 17/91 - A Little to the Left
    https://backloggd.com/u/SilentStorm63/logs/a-little-to-the-left/
🔍 18/91 - Lost in Random
    https://backloggd.com/u/SilentStorm63/logs/lost-in-random/
🔍 19/91 - What Remains of Edith Finch
    https://backloggd.com/u/SilentStorm63/logs/what-remains-of-edith-finch/
🔍 20/91 - Marvel's Spider-Man Remastered
    https://backloggd.com/u/SilentStorm63/logs/marvels-spider-man-remastered/
🔍 21/91 - Horizon Zero Dawn: Complete Edition
    https://backloggd.com/u/SilentStorm63/logs/horizon-zero-dawn-complete-edition/
🔍 22/91 - Core Keeper
    https://backloggd.com/u/SilentStorm63/logs/core-keeper/
🔍 23/91 - Rise of the Tomb Raider: 20 Year Celebration
    https://backloggd.com/u/SilentStorm63/logs/rise-of-the-tomb-raider-20-year-celebration/
🔍 24/91 - SSX 3
    https://backloggd.com/u/SilentStorm63/logs/ssx-3/
🔍 25/91 - Hue
    https://backloggd.com/u/SilentStorm63/logs/hue/
🔍 26/91 - Super Monkey Ball 2
    https://backloggd.com/u/SilentStorm63/logs/super-monkey-ball-2/
🔍 27/91 - Chants of Sennaar
    https://backloggd.com/u/SilentStorm63/logs/chants-of-sennaar/
🔍 28/91 - Gorogoa
    https://backloggd.com/u/SilentStorm63/logs/gorogoa/
🔍 29/91 - Deltarune
    https://backloggd.com/u/SilentStorm63/logs/deltarune/
🔍 30/91 - Diddy Kong Racing
    https://backloggd.com/u/SilentStorm63/logs/diddy-kong-racing/
🔍 31/91 - Doodle Jump
    https://backloggd.com/u/SilentStorm63/logs/doodle-jump/
🔍 32/91 - Wii Play
    https://backloggd.com/u/SilentStorm63/logs/wii-play/
🔍 33/91 - Twelve Minutes
    https://backloggd.com/u/SilentStorm63/logs/twelve-minutes/
🔍 34/91 - 2048
    https://backloggd.com/u/SilentStorm63/logs/2048/
🔍 35/91 - Jetpack Joyride
    https://backloggd.com/u/SilentStorm63/logs/jetpack-joyride/
🔍 36/91 - Crossy Road
    https://backloggd.com/u/SilentStorm63/logs/crossy-road/
🔍 37/91 - Ori and the Blind Forest: Definitive Edition
    https://backloggd.com/u/SilentStorm63/logs/ori-and-the-blind-forest-definitive-edition/
🔍 38/91 - Palworld
    https://backloggd.com/u/SilentStorm63/logs/palworld/
🔍 39/91 - The Legend of Zelda: Phantom Hourglass
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-phantom-hourglass/
🔍 40/91 - Phasmophobia
    https://backloggd.com/u/SilentStorm63/logs/phasmophobia/
🔍 41/91 - The Legend of Zelda: Twilight Princess
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-twilight-princess--1/
🔍 42/91 - Sid Meier's Civilization VI
    https://backloggd.com/u/SilentStorm63/logs/sid-meiers-civilization-vi/
🔍 43/91 - Guitar Hero III: Legends of Rock
    https://backloggd.com/u/SilentStorm63/logs/guitar-hero-iii-legends-of-rock/
🔍 44/91 - Flappy Bird
    https://backloggd.com/u/SilentStorm63/logs/flappy-bird/
🔍 45/91 - The Legend of Zelda: Skyward Sword
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-skyward-sword/
🔍 46/91 - Risk of Rain 2
    https://backloggd.com/u/SilentStorm63/logs/risk-of-rain-2/
🔍 47/91 - Baldur's Gate 3
    https://backloggd.com/u/SilentStorm63/logs/baldurs-gate-3/
🔍 48/91 - Genshin Impact
    https://backloggd.com/u/SilentStorm63/logs/genshin-impact/
🔍 49/91 - The Legend of Zelda: Tears of the Kingdom
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-tears-of-the-kingdom/
🔍 50/91 - Wii Sports
    https://backloggd.com/u/SilentStorm63/logs/wii-sports/
🔍 51/91 - Hollow Knight
    https://backloggd.com/u/SilentStorm63/logs/hollow-knight/
🔍 52/91 - Minecraft: Java Edition
    https://backloggd.com/u/SilentStorm63/logs/minecraft-java-edition/
🔍 53/91 - The Witness
    https://backloggd.com/u/SilentStorm63/logs/the-witness/
🔍 54/91 - Bloons TD 6
    https://backloggd.com/u/SilentStorm63/logs/bloons-td-6/
🔍 55/91 - Deltarune: Chapter 1
    https://backloggd.com/u/SilentStorm63/logs/deltarune-chapter-1/
🔍 56/91 - Destiny 2
    https://backloggd.com/u/SilentStorm63/logs/destiny-2/
🔍 57/91 - The Legend of Zelda: Skyward Sword HD
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-skyward-sword-hd/
🔍 58/91 - Shadow of the Tomb Raider
    https://backloggd.com/u/SilentStorm63/logs/shadow-of-the-tomb-raider/
🔍 59/91 - The Stanley Parable
    https://backloggd.com/u/SilentStorm63/logs/the-stanley-parable/
🔍 60/91 - The Wolf Among Us
    https://backloggd.com/u/SilentStorm63/logs/the-wolf-among-us/
🔍 61/91 - Splatoon 3
    https://backloggd.com/u/SilentStorm63/logs/splatoon-3/
🔍 62/91 - New Super Mario Bros. Wii
    https://backloggd.com/u/SilentStorm63/logs/new-super-mario-bros-wii/
🔍 63/91 - Mario Kart DS
    https://backloggd.com/u/SilentStorm63/logs/mario-kart-ds/
🔍 64/91 - Valorant
    https://backloggd.com/u/SilentStorm63/logs/valorant/
🔍 65/91 - Ori and the Blind Forest
    https://backloggd.com/u/SilentStorm63/logs/ori-and-the-blind-forest/
🔍 66/91 - Rise of the Tomb Raider
    https://backloggd.com/u/SilentStorm63/logs/rise-of-the-tomb-raider/
🔍 67/91 - The Legend of Zelda: Twilight Princess
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-twilight-princess/
🔍 68/91 - Ori and the Will of the Wisps
    https://backloggd.com/u/SilentStorm63/logs/ori-and-the-will-of-the-wisps/
🔍 69/91 - Indiana Jones and the Great Circle
    https://backloggd.com/u/SilentStorm63/logs/indiana-jones-and-the-great-circle/
🔍 70/91 - Super Smash Bros. Brawl
    https://backloggd.com/u/SilentStorm63/logs/super-smash-bros-brawl/
🔍 71/91 - Firewatch
    https://backloggd.com/u/SilentStorm63/logs/firewatch/
🔍 72/91 - Overwatch
    https://backloggd.com/u/SilentStorm63/logs/overwatch/
🔍 73/91 - The Legend of Zelda: Echoes of Wisdom
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-echoes-of-wisdom/
🔍 74/91 - Minecraft
    https://backloggd.com/u/SilentStorm63/logs/minecraft--1/
🔍 75/91 - Titanfall 2
    https://backloggd.com/u/SilentStorm63/logs/titanfall-2/
🔍 76/91 - Tomb Raider
    https://backloggd.com/u/SilentStorm63/logs/tomb-raider--2/
🔍 77/91 - Life is Strange
    https://backloggd.com/u/SilentStorm63/logs/life-is-strange/
🔍 78/91 - Mario Kart 8 Deluxe
    https://backloggd.com/u/SilentStorm63/logs/mario-kart-8-deluxe/
🔍 79/91 - Overwatch 2
    https://backloggd.com/u/SilentStorm63/logs/overwatch-2/
🔍 80/91 - Metroid Dread
    https://backloggd.com/u/SilentStorm63/logs/metroid-dread/
🔍 81/91 - Marvel's Spider-Man: Miles Morales
    https://backloggd.com/u/SilentStorm63/logs/marvels-spider-man-miles-morales/
🔍 82/91 - Stray
    https://backloggd.com/u/SilentStorm63/logs/stray/
🔍 83/91 - Among Us
    https://backloggd.com/u/SilentStorm63/logs/among-us/
🔍 84/91 - The Witcher 3: Wild Hunt
    https://backloggd.com/u/SilentStorm63/logs/the-witcher-3-wild-hunt/
🔍 85/91 - Super Mario Bros. Wonder
    https://backloggd.com/u/SilentStorm63/logs/super-mario-bros-wonder/
🔍 86/91 - Portal
    https://backloggd.com/u/SilentStorm63/logs/portal/
🔍 87/91 - God of War
    https://backloggd.com/u/SilentStorm63/logs/god-of-war--1/
🔍 88/91 - Portal 2
    https://backloggd.com/u/SilentStorm63/logs/portal-2/
🔍 89/91 - The Legend of Zelda: Breath of the Wild
    https://backloggd.com/u/SilentStorm63/logs/the-legend-of-zelda-breath-of-the-wild/
🔍 90/91 - Balatro
    https://backloggd.com/u/SilentStorm63/logs/balatro/
🔍 91/91 - Undertale
    https://backloggd.com/u/SilentStorm63/logs/undertale/

✅ Archivo generado: backloggd_juegos_con_logs.xlsx con 91 juegos.

In [3]:
import requests

# --- CONFIGURACIÓN ---
RAWG_API_KEY = "ddd05c91688a43bbad088303d18cf599"
juego_a_buscar = "Hollow Knight"  # puedes cambiar esto

# --- 1. Buscar juego por nombre ---
url_busqueda = "https://api.rawg.io/api/games"
params = {
    "search": juego_a_buscar,
    "key": RAWG_API_KEY,
    "page_size": 1
}

res_busqueda = requests.get(url_busqueda, params=params)
data = res_busqueda.json()

print("🔄 Respuesta completa:")
print(data)


if data["results"]:
    juego = data["results"][0]
    slug = juego["slug"]
    print(f"🎯 Juego encontrado: {juego['name']} (slug: {slug})")

    # --- 2. Obtener detalles completos del juego ---
    url_detalle = f"https://api.rawg.io/api/games/{slug}?key={RAWG_API_KEY}"
    res_detalle = requests.get(url_detalle)
    detalle = res_detalle.json()

    # --- 3. Extraer información ---
    info = {
        "Nombre RAWG": juego.get("name", ""),
        "Géneros": ", ".join([g["name"] for g in juego.get("genres", [])]),
        "Desarrollador": ", ".join([d["name"] for d in detalle.get("developers", [])]) if "developers" in detalle else "",
        "Plataformas": ", ".join([p["platform"]["name"] for p in juego.get("platforms", [])]),
        "Fecha de salida": juego.get("released", ""),
        "Metacritic": juego.get("metacritic", "")
    }

    # --- 4. Mostrar resultado ---
    print("\n🧾 Información obtenida:")
    for k, v in info.items():
        print(f"{k}: {v}")
else:
    print("❌ No se encontró el juego en RAWG.")

🔄 Respuesta completa:
{'count': 16467, 'next': 'https://api.rawg.io/api/games?key=ddd05c91688a43bbad088303d18cf599&page=2&page_size=1&search=Hollow+Knight', 'previous': None, 'results': [{'slug': 'hollow-knight', 'name': 'Hollow Knight', 'playtime': 7, 'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 1, 'name': 'Xbox One', 'slug': 'xbox-one'}}, {'platform': {'id': 18, 'name': 'PlayStation 4', 'slug': 'playstation4'}}, {'platform': {'id': 7, 'name': 'Nintendo Switch', 'slug': 'nintendo-switch'}}, {'platform': {'id': 5, 'name': 'macOS', 'slug': 'macos'}}, {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}], 'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}, {'store': {'id': 3, 'name': 'PlayStation Store', 'slug': 'playstation-store'}}, {'store': {'id': 2, 'name': 'Xbox Store', 'slug': 'xbox-store'}}, {'store': {'id': 5, 'name': 'GOG', 'slug': 'gog'}}, {'store': {'id': 6, 'name': 'Nintendo Store', 'slug': 'nintendo'}}], 'released': '2017-02-23', 'tba': False, 'background_image': 'https://media.rawg.io/media/games/4cf/4cfc6b7f1850590a4634b08bfab308ab.jpg', 'rating': 4.4, 'rating_top': 5, 'ratings': [{'id': 5, 'title': 'exceptional', 'count': 1647, 'percent': 62.13}, {'id': 4, 'title': 'recommended', 'count': 678, 'percent': 25.58}, {'id': 3, 'title': 'meh', 'count': 200, 'percent': 7.54}, {'id': 1, 'title': 'skip', 'count': 126, 'percent': 4.75}], 'ratings_count': 2594, 'reviews_text_count': 34, 'added': 11533, 'added_by_status': {'yet': 852, 'owned': 6958, 'beaten': 1642, 'toplay': 648, 'dropped': 909, 'playing': 524}, 'metacritic': 88, 'suggestions_count': 514, 'updated': '2025-05-04T04:25:52', 'id': 9767, 'score': '83.11638', 'clip': None, 'tags': [{'id': 31, 'name': 'Singleplayer', 'slug': 'singleplayer', 'language': 'eng', 'games_count': 239234, 'image_background': 'https://media.rawg.io/media/games/8cc/8cce7c0e99dcc43d66c8efd42f9d03e3.jpg'}, {'id': 42396, 'name': 'Для одного игрока', 'slug': 'dlia-odnogo-igroka', 'language': 'rus', 'games_count': 61308, 'image_background': 'https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg'}, {'id': 42417, 'name': 'Экшен', 'slug': 'ekshen', 'language': 'rus', 'games_count': 46069, 'image_background': 'https://media.rawg.io/media/games/6fc/6fcf4cd3b17c288821388e6085bb0fc9.jpg'}, {'id': 42392, 'name': 'Приключение', 'slug': 'prikliuchenie', 'language': 'rus', 'games_count': 44368, 'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'}, {'id': 40847, 'name': 'Steam Achievements', 'slug': 'steam-achievements', 'language': 'eng', 'games_count': 45479, 'image_background': 'https://media.rawg.io/media/games/120/1201a40e4364557b124392ee50317b99.jpg'}, {'id': 42398, 'name': 'Инди', 'slug': 'indi-2', 'language': 'rus', 'games_count': 62491, 'image_background': 'https://media.rawg.io/media/games/f99/f9979698c43fd84c3ab69280576dd3af.jpg'}, {'id': 40836, 'name': 'Full controller support', 'slug': 'full-controller-support', 'language': 'eng', 'games_count': 21435, 'image_background': 'https://media.rawg.io/media/games/737/737ea5662211d2e0bbd6f5989189e4f1.jpg'}, {'id': 40849, 'name': 'Steam Cloud', 'slug': 'steam-cloud', 'language': 'eng', 'games_count': 22082, 'image_background': 'https://media.rawg.io/media/games/48c/48cb04ca483be865e3a83119c94e6097.jpg'}, {'id': 13, 'name': 'Atmospheric', 'slug': 'atmospheric', 'language': 'eng', 'games_count': 36888, 'image_background': 'https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg'}, {'id': 42400, 'name': 'Атмосфера', 'slug': 'atmosfera', 'language': 'rus', 'games_count': 6083, 'image_background': 'https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg'}, {'id': 7808, 'name': 'steam-trading-cards', 'slug': 'steam-trading-cards', 'language': 'eng', 'games_count': 7568, 'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'}, {'id': 42401, 'name': 'Отличный саундтрек', 'slug': 'otlichnyi-saundtrek', 'language': 'rus', 'games_count': 4651, 'image_background': 'https://media.rawg.io/media/games/7a2/7a2500ee8b2c0e1ff268bb4479463dea.jpg'}, {'id': 42, 'name': 'Great Soundtrack', 'slug': 'great-soundtrack', 'language': 'eng', 'games_count': 3427, 'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'}, {'id': 42394, 'name': 'Глубокий сюжет', 'slug': 'glubokii-siuzhet', 'language': 'rus', 'games_count': 15704, 'image_background': 'https://media.rawg.io/media/games/6c5/6c55e22185876626881b76c11922b073.jpg'}, {'id': 118, 'name': 'Story Rich', 'slug': 'story-rich', 'language': 'eng', 'games_count': 24838, 'image_background': 'https://media.rawg.io/media/games/6cd/6cd653e0aaef5ff8bbd295bf4bcb12eb.jpg'}, {'id': 42442, 'name': 'Открытый мир', 'slug': 'otkrytyi-mir', 'language': 'rus', 'games_count': 6731, 'image_background': 'https://media.rawg.io/media/games/310/3106b0e012271c5ffb16497b070be739.jpg'}, {'id': 36, 'name': 'Open World', 'slug': 'open-world', 'language': 'eng', 'games_count': 8544, 'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'}, {'id': 45, 'name': '2D', 'slug': '2d', 'language': 'eng', 'games_count': 202418, 'image_background': 'https://media.rawg.io/media/games/f8c/f8c6a262ead4c16b47e1219310210eb3.jpg'}, {'id': 42420, 'name': 'Сложная', 'slug': 'slozhnaia', 'language': 'rus', 'games_count': 5914, 'image_background': 'https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg'}, {'id': 49, 'name': 'Difficult', 'slug': 'difficult', 'language': 'eng', 'games_count': 13886, 'image_background': 'https://media.rawg.io/media/games/48e/48e63bbddeddbe9ba81942772b156664.jpg'}, {'id': 6, 'name': 'Exploration', 'slug': 'exploration', 'language': 'eng', 'games_count': 26559, 'image_background': 'https://media.rawg.io/media/games/d7d/d7d33daa1892e2468cd0263d5dfc957e.jpg'}, {'id': 42463, 'name': 'Платформер', 'slug': 'platformer-2', 'language': 'rus', 'games_count': 10163, 'image_background': 'https://media.rawg.io/media/games/c89/c89ca70716080733d03724277df2c6c7.jpg'}, {'id': 42464, 'name': 'Исследование', 'slug': 'issledovanie', 'language': 'rus', 'games_count': 2979, 'image_background': 'https://media.rawg.io/media/games/da1/da1b267764d77221f07a4386b6548e5a.jpg'}, {'id': 42416, 'name': 'Контроллер', 'slug': 'kontroller', 'language': 'rus', 'games_count': 8007, 'image_background': 'https://media.rawg.io/media/games/e4a/e4ab7f784bdc38c76ce6e4cef9715d18.jpg'}, {'id': 115, 'name': 'Controller', 'slug': 'controller', 'language': 'eng', 'games_count': 13561, 'image_background': 'https://media.rawg.io/media/games/35b/35b47c4d85cd6e08f3e2ca43ea5ce7bb.jpg'}, {'id': 42586, 'name': 'Милая', 'slug': 'milaia', 'language': 'rus', 'games_count': 16108, 'image_background': 'https://media.rawg.io/media/games/096/0962642c3f74cd6306ad8bfdfd3d6150.jpg'}, {'id': 336, 'name': 'controller support', 'slug': 'controller-support', 'language': 'eng', 'games_count': 293, 'image_background': 'https://media.rawg.io/media/games/f46/f466571d536f2e3ea9e815ad17177501.jpg'}, {'id': 88, 'name': 'Cute', 'slug': 'cute', 'language': 'eng', 'games_count': 37027, 'image_background': 'https://media.rawg.io/media/games/04a/04a7e7e185fb51493bdcbe1693a8b3dc.jpg'}, {'id': 42469, 'name': 'Вид сбоку', 'slug': 'vid-sboku', 'language': 'rus', 'games_count': 4882, 'image_background': 'https://media.rawg.io/media/games/595/59556e1839b2e79b6f11f2c68a197663.jpg'}, {'id': 42506, 'name': 'Тёмное фэнтези', 'slug': 'tiomnoe-fentezi', 'language': 'rus', 'games_count': 3726, 'image_background': 'https://media.rawg.io/media/games/b4a/b4adf80c36e267b35acc3497ed2af19c.jpg'}, {'id': 40, 'name': 'Dark Fantasy', 'slug': 'dark-fantasy', 'language': 'eng', 'games_count': 5037, 'image_background': 'https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg'}, {'id': 113, 'name': 'Side Scroller', 'slug': 'side-scroller', 'language': 'eng', 'games_count': 11260, 'image_background': 'https://media.rawg.io/media/games/f90/f90ee1a4239247a822771c40488e68c5.jpg'}, {'id': 218, 'name': 'Multiple Endings', 'slug': 'multiple-endings', 'language': 'eng', 'games_count': 10366, 'image_background': 'https://media.rawg.io/media/games/3b5/3b56220d6038b8b1ad66c4d05ef95215.jpg'}, {'id': 259, 'name': 'Metroidvania', 'slug': 'metroidvania', 'language': 'eng', 'games_count': 4541, 'image_background': 'https://media.rawg.io/media/games/559/559bc0768f656ad0c63c54b80a82d680.jpg'}, {'id': 42508, 'name': 'Нелинейность', 'slug': 'nelineinost', 'language': 'rus', 'games_count': 1017, 'image_background': 'https://media.rawg.io/media/games/b28/b28a135fa6133e17b228f46902a4fda4.jpg'}, {'id': 42462, 'name': 'Метроидвания', 'slug': 'metroidvaniia', 'language': 'rus', 'games_count': 1453, 'image_background': 'https://media.rawg.io/media/screenshots/2ff/2ffe731b3388bd795f94c38e9afed60f.jpg'}, {'id': 42483, 'name': 'Рисованная графика', 'slug': 'risovannaia-grafika', 'language': 'rus', 'games_count': 5504, 'image_background': 'https://media.rawg.io/media/games/eeb/eeb9e668da5fd07bab9f655acfbbe579.jpg'}, {'id': 258, 'name': 'Hand-drawn', 'slug': 'hand-drawn', 'language': 'eng', 'games_count': 8386, 'image_background': 'https://media.rawg.io/media/games/8cd/8cd179c85bd3de8f79bef245b15075fb.jpg'}, {'id': 42592, 'name': 'Похожа на Dark Souls', 'slug': 'pokhozha-na-dark-souls', 'language': 'rus', 'games_count': 1266, 'image_background': 'https://media.rawg.io/media/games/d4a/d4a85e0d7676e4f9bce23f349e44e75e.jpg'}, {'id': 204, 'name': 'Gothic', 'slug': 'gothic', 'language': 'eng', 'games_count': 1061, 'image_background': 'https://media.rawg.io/media/games/0b5/0b5410b1e4b3fb72696dcefbf4f1cf40.jpg'}], 'esrb_rating': {'id': 2, 'name': 'Everyone 10+', 'slug': 'everyone-10-plus', 'name_en': 'Everyone 10+', 'name_ru': 'С 10 лет'}, 'user_game': None, 'reviews_count': 2651, 'saturated_color': '0f0f0f', 'dominant_color': '0f0f0f', 'short_screenshots': [{'id': -1, 'image': 'https://media.rawg.io/media/games/4cf/4cfc6b7f1850590a4634b08bfab308ab.jpg'}, {'id': 72619, 'image': 'https://media.rawg.io/media/screenshots/6b3/6b309936c1fe07e9b7fa5e62a372790d.jpg'}, {'id': 72620, 'image': 'https://media.rawg.io/media/screenshots/1a7/1a7a69db58c19d323f1dfbcc340d3f1e.jpg'}, {'id': 72621, 'image': 'https://media.rawg.io/media/screenshots/723/7237d0c546b0d17a6a226f38823081d4.jpg'}, {'id': 72622, 'image': 'https://media.rawg.io/media/screenshots/331/331095489397e7387681d921e8e472d4.jpg'}, {'id': 72623, 'image': 'https://media.rawg.io/media/screenshots/5db/5db89e896496352c8f0a0a0bd545bd6d.jpg'}, {'id': 72624, 'image': 'https://media.rawg.io/media/screenshots/843/843e06c9c5b26c309b47bd7075320dae.jpg'}], 'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}}, {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}, {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}}, {'platform': {'id': 6, 'name': 'Linux', 'slug': 'linux'}}, {'platform': {'id': 7, 'name': 'Nintendo', 'slug': 'nintendo'}}], 'genres': [{'id': 83, 'name': 'Platformer', 'slug': 'platformer'}, {'id': 51, 'name': 'Indie', 'slug': 'indie'}, {'id': 4, 'name': 'Action', 'slug': 'action'}]}], 'user_platforms': False}
🎯 Juego encontrado: Hollow Knight (slug: hollow-knight)

🧾 Información obtenida:
Nombre RAWG: Hollow Knight
Géneros: Platformer, Indie, Action
Desarrollador: Team Cherry
Plataformas: PC, Xbox One, PlayStation 4, Nintendo Switch, macOS, Linux
Fecha de salida: 2017-02-23
Metacritic: 88

# Prueba para leer 1 o 2 juegos

In [4]:
import pandas as pd

# Mini subconjunto de prueba
df_prueba = pd.DataFrame([
    {"Juego": "Fortnite"},
    {"Juego": "The Last of Us Part I"},
    {"Juego": "Hollow Knight"},
])

df_prueba.to_excel("backloggd_juegos_prueba.xlsx", index=False)

In [6]:
import pandas as pd
import requests
import time

API_KEY = "ddd05c91688a43bbad088303d18cf599"
ARCHIVO_ENTRADA = "backloggd_juegos_prueba.xlsx"
ARCHIVO_SALIDA = "backloggd_juegos_prueba_enriquecido.xlsx"

df = pd.read_excel(ARCHIVO_ENTRADA)

# Agregar columnas si no existen
for col in ["Nombre RAWG", "Géneros", "Desarrollador", "Plataformas", "Fecha de salida", "Metacritic"]:
    if col not in df.columns:
        df[col] = ""

def obtener_datos_rawg(nombre):
    try:
        url_busqueda = "https://api.rawg.io/api/games"
        params = {"search": nombre, "key": API_KEY, "page_size": 1}
        res = requests.get(url_busqueda, params=params)

        print(f"🔎 Buscando: {nombre}")
        print(f"🛰 Status: {res.status_code}")

        if res.status_code != 200:
            return None

        data = res.json()
        print(f"📦 Respuesta: {data}")

        if not data.get("results"):
            return None

        juego = data["results"][0]
        slug = juego.get("slug", "")

        detalle_url = f"https://api.rawg.io/api/games/{slug}?key={API_KEY}"
        detalle = requests.get(detalle_url).json()

        return {
            "Nombre RAWG": juego.get("name", ""),
            "Géneros": ", ".join([g["name"] for g in juego.get("genres", [])]),
            "Desarrollador": ", ".join([d["name"] for d in detalle.get("developers", [])]) if "developers" in detalle else "",
            "Plataformas": ", ".join([p["platform"]["name"] for p in juego.get("platforms", [])]),
            "Fecha de salida": juego.get("released", ""),
            "Metacritic": juego.get("metacritic", "")
        }
    except Exception as e:
        print(f"⚠️ Error con '{nombre}': {e}")
        return None

# Procesar solo 3 juegos
for index, row in df.iterrows():
    nombre = row["Juego"]
    datos = obtener_datos_rawg(nombre)

    if datos:
        for key, value in datos.items():
            df.at[index, key] = value

    time.sleep(2.5)  # espera para evitar rate limit

df.to_excel(ARCHIVO_SALIDA, index=False)
print(f"\n✅ Archivo generado: {ARCHIVO_SALIDA}")

🔎 Buscando: Fortnite
🛰 Status: 200
📦 Respuesta: {'count': 174, 'next': 'https://api.rawg.io/api/games?key=ddd05c91688a43bbad088303d18cf599&page=2&page_size=1&search=Fortnite', 'previous': None, 'results': [{'slug': 'fornite-battle-royale', 'name': 'Fortnite Battle Royale', 'playtime': 0, 'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 187, 'name': 'PlayStation 5', 'slug': 'playstation5'}}, {'platform': {'id': 18, 'name': 'PlayStation 4', 'slug': 'playstation4'}}, {'platform': {'id': 1, 'name': 'Xbox One', 'slug': 'xbox-one'}}, {'platform': {'id': 186, 'name': 'Xbox Series S/X', 'slug': 'xbox-series-x'}}, {'platform': {'id': 7, 'name': 'Nintendo Switch', 'slug': 'nintendo-switch'}}, {'platform': {'id': 3, 'name': 'iOS', 'slug': 'ios'}}, {'platform': {'id': 21, 'name': 'Android', 'slug': 'android'}}], 'stores': [{'store': {'id': 3, 'name': 'PlayStation Store', 'slug': 'playstation-store'}}, {'store': {'id': 2, 'name': 'Xbox Store', 'slug': 'xbox-store'}}, {'store': {'id': 4, 'name': 'App Store', 'slug': 'apple-appstore'}}, {'store': {'id': 6, 'name': 'Nintendo Store', 'slug': 'nintendo'}}, {'store': {'id': 11, 'name': 'Epic Games', 'slug': 'epic-games'}}], 'released': '2017-09-26', 'tba': False, 'background_image': 'https://media.rawg.io/media/games/dcb/dcbb67f371a9a28ea38ffd73ee0f53f3.jpg', 'rating': 3.27, 'rating_top': 4, 'ratings': [{'id': 4, 'title': 'recommended', 'count': 413, 'percent': 36.48}, {'id': 3, 'title': 'meh', 'count': 405, 'percent': 35.78}, {'id': 1, 'title': 'skip', 'count': 183, 'percent': 16.17}, {'id': 5, 'title': 'exceptional', 'count': 131, 'percent': 11.57}], 'ratings_count': 1103, 'reviews_text_count': 21, 'added': 5287, 'added_by_status': {'yet': 48, 'owned': 3801, 'beaten': 226, 'toplay': 59, 'dropped': 883, 'playing': 270}, 'metacritic': None, 'suggestions_count': 543, 'updated': '2025-05-07T18:00:41', 'id': 47137, 'score': '75.284424', 'clip': None, 'tags': [{'id': 7, 'name': 'Multiplayer', 'slug': 'multiplayer', 'language': 'eng', 'games_count': 40632, 'image_background': 'https://media.rawg.io/media/games/6c5/6c55e22185876626881b76c11922b073.jpg'}, {'id': 32, 'name': 'Sci-fi', 'slug': 'sci-fi', 'language': 'eng', 'games_count': 20840, 'image_background': 'https://media.rawg.io/media/games/b7d/b7d3f1715fa8381a4e780173a197a615.jpg'}, {'id': 37, 'name': 'Sandbox', 'slug': 'sandbox', 'language': 'eng', 'games_count': 7795, 'image_background': 'https://media.rawg.io/media/games/713/713269608dc8f2f40f5a670a14b2de94.jpg'}, {'id': 123, 'name': 'Comedy', 'slug': 'comedy', 'language': 'eng', 'games_count': 13805, 'image_background': 'https://media.rawg.io/media/games/e04/e04963f3ac4c4fa83a1dc0b9231e50db.jpg'}, {'id': 79, 'name': 'Free to Play', 'slug': 'free-to-play', 'language': 'eng', 'games_count': 8566, 'image_background': 'https://media.rawg.io/media/games/b7b/b7b8381707152afc7d91f5d95de70e39.jpg'}, {'id': 571, 'name': '3D', 'slug': '3d', 'language': 'eng', 'games_count': 89372, 'image_background': 'https://media.rawg.io/media/games/a3e/a3ea71c18e81d54ebaf982dadb9a8738.jpg'}, {'id': 997, 'name': 'island', 'slug': 'island', 'language': 'eng', 'games_count': 2647, 'image_background': 'https://media.rawg.io/media/games/08e/08e8d09cd5aae30959c4486649fda3e6.jpg'}, {'id': 35162, 'name': 'Battle Royale', 'slug': 'battle-royale-2', 'language': 'eng', 'games_count': 836, 'image_background': 'https://media.rawg.io/media/games/578/578dc93c4b968ae544f0e9af5017bc91.jpg'}, {'id': 1411, 'name': 'build', 'slug': 'build', 'language': 'eng', 'games_count': 5041, 'image_background': 'https://media.rawg.io/media/games/431/4317e294e88e4c9d77327693b15f499a.jpg'}, {'id': 500, 'name': 'Solo', 'slug': 'solo', 'language': 'eng', 'games_count': 1637, 'image_background': 'https://media.rawg.io/media/games/9f1/9f1891779cb20f44de93cef33b067e50.jpg'}, {'id': 2406, 'name': 'dance', 'slug': 'dance', 'language': 'eng', 'games_count': 1160, 'image_background': 'https://media.rawg.io/media/screenshots/49b/49bedabd608df3bb793abe089b496319.jpg'}, {'id': 499, 'name': 'Team', 'slug': 'team', 'language': 'eng', 'games_count': 24, 'image_background': 'https://media.rawg.io/media/screenshots/87f/87f4fe4138cc8f0829acceb37dbe1734.jpg'}, {'id': 1911, 'name': 'bus', 'slug': 'bus', 'language': 'eng', 'games_count': 110, 'image_background': 'https://media.rawg.io/media/screenshots/692/692f8dc416fc39fa01303a98efa3e354_nwINMIz.jpg'}], 'esrb_rating': {'id': 3, 'name': 'Teen', 'slug': 'teen', 'name_en': 'Teen', 'name_ru': 'С 13 лет'}, 'user_game': None, 'reviews_count': 1132, 'saturated_color': '0f0f0f', 'dominant_color': '0f0f0f', 'short_screenshots': [{'id': -1, 'image': 'https://media.rawg.io/media/games/dcb/dcbb67f371a9a28ea38ffd73ee0f53f3.jpg'}, {'id': 663657, 'image': 'https://media.rawg.io/media/screenshots/c28/c286227823231c426a88aa873cf1b8d6.jpg'}, {'id': 663658, 'image': 'https://media.rawg.io/media/screenshots/0bf/0bf03856d787e721c6e16fb45531c6f1.jpg'}, {'id': 663659, 'image': 'https://media.rawg.io/media/screenshots/b85/b85077de89230bf2b3cdf2c41e77acdc.jpg'}, {'id': 663660, 'image': 'https://media.rawg.io/media/screenshots/d12/d1229ab5948538540d14a0370ab6e7c4.jpg'}, {'id': 663661, 'image': 'https://media.rawg.io/media/screenshots/7e1/7e19fc248d16d15376ee7550f515dea1.jpg'}, {'id': 663662, 'image': 'https://media.rawg.io/media/screenshots/7ac/7acd1c484070110647740d85ac164609.jpg'}], 'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}}, {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}, {'platform': {'id': 4, 'name': 'iOS', 'slug': 'ios'}}, {'platform': {'id': 8, 'name': 'Android', 'slug': 'android'}}, {'platform': {'id': 7, 'name': 'Nintendo', 'slug': 'nintendo'}}], 'genres': [{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}, {'id': 4, 'name': 'Action', 'slug': 'action'}]}], 'user_platforms': False}
🔎 Buscando: The Last of Us Part I
🛰 Status: 200
📦 Respuesta: {'count': 141449, 'next': 'https://api.rawg.io/api/games?key=ddd05c91688a43bbad088303d18cf599&page=2&page_size=1&search=The+Last+of+Us+Part+I', 'previous': None, 'results': [{'slug': 'the-last-of-us-part-i', 'name': 'The Last of Us Part I', 'playtime': 13, 'platforms': [{'platform': {'id': 4, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 187, 'name': 'PlayStation 5', 'slug': 'playstation5'}}], 'stores': [{'store': {'id': 1, 'name': 'Steam', 'slug': 'steam'}}, {'store': {'id': 3, 'name': 'PlayStation Store', 'slug': 'playstation-store'}}, {'store': {'id': 11, 'name': 'Epic Games', 'slug': 'epic-games'}}], 'released': '2022-09-02', 'tba': False, 'background_image': 'https://media.rawg.io/media/games/71d/71df9e759b2246f9769126c98ac997fc.jpg', 'rating': 4.67, 'rating_top': 5, 'ratings': [{'id': 5, 'title': 'exceptional', 'count': 339, 'percent': 75.84}, {'id': 4, 'title': 'recommended', 'count': 82, 'percent': 18.34}, {'id': 3, 'title': 'meh', 'count': 19, 'percent': 4.25}, {'id': 1, 'title': 'skip', 'count': 7, 'percent': 1.57}], 'ratings_count': 433, 'reviews_text_count': 9, 'added': 1637, 'added_by_status': {'yet': 143, 'owned': 480, 'beaten': 541, 'toplay': 383, 'dropped': 46, 'playing': 44}, 'metacritic': None, 'suggestions_count': 574, 'updated': '2025-05-07T20:58:26', 'id': 799265, 'score': '79.00783', 'clip': None, 'tags': [{'id': 31, 'name': 'Singleplayer', 'slug': 'singleplayer', 'language': 'eng', 'games_count': 239144, 'image_background': 'https://media.rawg.io/media/games/73e/73eecb8909e0c39fb246f457b5d6cbbe.jpg'}, {'id': 42396, 'name': 'Для одного игрока', 'slug': 'dlia-odnogo-igroka', 'language': 'rus', 'games_count': 61235, 'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'}, {'id': 42417, 'name': 'Экшен', 'slug': 'ekshen', 'language': 'rus', 'games_count': 46035, 'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'}, {'id': 42392, 'name': 'Приключение', 'slug': 'prikliuchenie', 'language': 'rus', 'games_count': 44328, 'image_background': 'https://media.rawg.io/media/games/49c/49c3dfa4ce2f6f140cc4825868e858cb.jpg'}, {'id': 40847, 'name': 'Steam Achievements', 'slug': 'steam-achievements', 'language': 'eng', 'games_count': 45430, 'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'}, {'id': 7, 'name': 'Multiplayer', 'slug': 'multiplayer', 'language': 'eng', 'games_count': 40624, 'image_background': 'https://media.rawg.io/media/games/6c5/6c55e22185876626881b76c11922b073.jpg'}, {'id': 40836, 'name': 'Full controller support', 'slug': 'full-controller-support', 'language': 'eng', 'games_count': 21419, 'image_background': 'https://media.rawg.io/media/games/4be/4be6a6ad0364751a96229c56bf69be59.jpg'}, {'id': 40849, 'name': 'Steam Cloud', 'slug': 'steam-cloud', 'language': 'eng', 'games_count': 22047, 'image_background': 'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg'}, {'id': 13, 'name': 'Atmospheric', 'slug': 'atmospheric', 'language': 'eng', 'games_count': 36877, 'image_background': 'https://media.rawg.io/media/games/737/737ea5662211d2e0bbd6f5989189e4f1.jpg'}, {'id': 42425, 'name': 'Для нескольких игроков', 'slug': 'dlia-neskolkikh-igrokov', 'language': 'rus', 'games_count': 11608, 'image_background': 'https://media.rawg.io/media/games/713/713269608dc8f2f40f5a670a14b2de94.jpg'}, {'id': 42401, 'name': 'Отличный саундтрек', 'slug': 'otlichnyi-saundtrek', 'language': 'rus', 'games_count': 4650, 'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}, {'id': 42, 'name': 'Great Soundtrack', 'slug': 'great-soundtrack', 'language': 'eng', 'games_count': 3426, 'image_background': 'https://media.rawg.io/media/games/198/1988a337305e008b41d7f536ce9b73f6.jpg'}, {'id': 42394, 'name': 'Глубокий сюжет', 'slug': 'glubokii-siuzhet', 'language': 'rus', 'games_count': 15679, 'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'}, {'id': 118, 'name': 'Story Rich', 'slug': 'story-rich', 'language': 'eng', 'games_count': 24813, 'image_background': 'https://media.rawg.io/media/games/6cd/6cd653e0aaef5ff8bbd295bf4bcb12eb.jpg'}, {'id': 42441, 'name': 'От третьего лица', 'slug': 'ot-tretego-litsa', 'language': 'rus', 'games_count': 8881, 'image_background': 'https://media.rawg.io/media/games/960/960b601d9541cec776c5fa42a00bf6c4.jpg'}, {'id': 149, 'name': 'Third Person', 'slug': 'third-person', 'language': 'eng', 'games_count': 13356, 'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'}, {'id': 16, 'name': 'Horror', 'slug': 'horror', 'language': 'eng', 'games_count': 47107, 'image_background': 'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg'}, {'id': 42491, 'name': 'Мясо', 'slug': 'miaso', 'language': 'rus', 'games_count': 4962, 'image_background': 'https://media.rawg.io/media/games/cee/cee577e2097a59b77193fe2bce94667d.jpg'}, {'id': 26, 'name': 'Gore', 'slug': 'gore', 'language': 'eng', 'games_count': 6216, 'image_background': 'https://media.rawg.io/media/games/c80/c80bcf321da44d69b18a06c04d942662.jpg'}, {'id': 42402, 'name': 'Насилие', 'slug': 'nasilie', 'language': 'rus', 'games_count': 6263, 'image_background': 'https://media.rawg.io/media/games/569/56978b5a77f13aa2ec5d09ec81d01cad.jpg'}, {'id': 34, 'name': 'Violent', 'slug': 'violent', 'language': 'eng', 'games_count': 7301, 'image_background': 'https://media.rawg.io/media/games/0af/0af85e8edddfa55368e47c539914a220.jpg'}, {'id': 69, 'name': 'Action-Adventure', 'slug': 'action-adventure', 'language': 'eng', 'games_count': 19131, 'image_background': 'https://media.rawg.io/media/games/67f/67f62d1f062a6164f57575e0604ee9f6.jpg'}, {'id': 42446, 'name': 'Шутер от третьего лица', 'slug': 'shuter-ot-tretego-litsa', 'language': 'rus', 'games_count': 2483, 'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'}, {'id': 150, 'name': 'Third-Person Shooter', 'slug': 'third-person-shooter', 'language': 'eng', 'games_count': 3874, 'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'}, {'id': 63, 'name': 'Zombies', 'slug': 'zombies', 'language': 'eng', 'games_count': 10834, 'image_background': 'https://media.rawg.io/media/games/198/1988a337305e008b41d7f536ce9b73f6.jpg'}, {'id': 42544, 'name': 'Зомби', 'slug': 'zombi-2', 'language': 'rus', 'games_count': 3190, 'image_background': 'https://media.rawg.io/media/games/198/1988a337305e008b41d7f536ce9b73f6.jpg'}, {'id': 42490, 'name': 'Приключенческий экшен', 'slug': 'prikliuchencheskii-ekshen', 'language': 'rus', 'games_count': 11524, 'image_background': 'https://media.rawg.io/media/games/686/686909717c3aa01518bc42ae2bf4259e.jpg'}, {'id': 42471, 'name': 'Хоррор на выживание', 'slug': 'khorror-na-vyzhivanie', 'language': 'rus', 'games_count': 3933, 'image_background': 'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg'}, {'id': 17, 'name': 'Survival Horror', 'slug': 'survival-horror', 'language': 'eng', 'games_count': 9295, 'image_background': 'https://media.rawg.io/media/games/1be/1be575aa6de86de328433a63fb534d9a.jpg'}, {'id': 43, 'name': 'Post-apocalyptic', 'slug': 'post-apocalyptic', 'language': 'eng', 'games_count': 4518, 'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'}, {'id': 77, 'name': 'Realistic', 'slug': 'realistic', 'language': 'eng', 'games_count': 7756, 'image_background': 'https://media.rawg.io/media/games/c3b/c3be1d5f55cb9324c97ccb7aaaf42ad4.jpg'}, {'id': 110, 'name': 'Cinematic', 'slug': 'cinematic', 'language': 'eng', 'games_count': 2859, 'image_background': 'https://media.rawg.io/media/games/a79/a79d2fc90c4dbf07a8580b19600fd61d.jpg'}, {'id': 42623, 'name': 'Кинематографичная', 'slug': 'kinematografichnaia', 'language': 'rus', 'games_count': 2767, 'image_background': 'https://media.rawg.io/media/games/708/7080e6c87e0825cb02888bf3c44b3889.jpg'}, {'id': 271, 'name': 'Remake', 'slug': 'remake', 'language': 'eng', 'games_count': 1725, 'image_background': 'https://media.rawg.io/media/games/d54/d54f0267a042f44c032d8ca264584ecf.jpg'}, {'id': 58132, 'name': 'Атмосферная', 'slug': 'atmosfernaia', 'language': 'rus', 'games_count': 12580, 'image_background': 'https://media.rawg.io/media/screenshots/a2e/a2ecf055ac9339d3a58808842c44a9b7.jpg'}, {'id': 209, 'name': 'Drama', 'slug': 'drama', 'language': 'eng', 'games_count': 5153, 'image_background': 'https://media.rawg.io/media/games/643/6431f15213a854efd273943f2cf6a925.jpg'}, {'id': 42691, 'name': 'Эмоциональная', 'slug': 'emotsionalnaia', 'language': 'rus', 'games_count': 3678, 'image_background': 'https://media.rawg.io/media/games/473/473bd9a5e9522629d6cb28b701fb836a.jpg'}, {'id': 42650, 'name': 'Драма', 'slug': 'drama-2', 'language': 'rus', 'games_count': 4542, 'image_background': 'https://media.rawg.io/media/games/b32/b32735e3f7d95959cc39265f555f2aa8.jpg'}, {'id': 572, 'name': 'Emotional', 'slug': 'emotional', 'language': 'eng', 'games_count': 3792, 'image_background': 'https://media.rawg.io/media/games/7ad/7adc6352280fe0e6626902e444e22195.jpg'}, {'id': 43374, 'name': 'Remote Play on TV', 'slug': 'remote-play-on-tv', 'language': 'eng', 'games_count': 555, 'image_background': 'https://media.rawg.io/media/games/59d/59d539fc7d8086ed9ea4f077c0196367.jpg'}, {'id': 64326, 'name': 'Постапокалипсис', 'slug': 'postapokalipsis', 'language': 'eng', 'games_count': 2144, 'image_background': 'https://media.rawg.io/media/games/b97/b97f47949ef696b99ed9e9160e89fb12.jpg'}, {'id': 78619, 'name': 'Ремейк', 'slug': 'remeik', 'language': 'eng', 'games_count': 77, 'image_background': 'https://media.rawg.io/media/games/fb0/fb00c8c4ecedcee9016e2a85023a6e15.jpg'}], 'esrb_rating': {'id': 4, 'name': 'Mature', 'slug': 'mature', 'name_en': 'Mature', 'name_ru': 'С 17 лет'}, 'user_game': None, 'reviews_count': 447, 'saturated_color': '0f0f0f', 'dominant_color': '0f0f0f', 'short_screenshots': [{'id': -1, 'image': 'https://media.rawg.io/media/games/71d/71df9e759b2246f9769126c98ac997fc.jpg'}, {'id': 3412523, 'image': 'https://media.rawg.io/media/screenshots/723/7232dfba2a746be21a0e8548b5333dd7.jpg'}, {'id': 3412531, 'image': 'https://media.rawg.io/media/screenshots/eb5/eb5a0522dbb56b8f698ac3fa8b884341.jpg'}, {'id': 3412532, 'image': 'https://media.rawg.io/media/screenshots/b0f/b0f8ff8c24bc46ca70a20ee4b83d9569.jpg'}, {'id': 3412533, 'image': 'https://media.rawg.io/media/screenshots/276/276688cddf9531e6cbcccc3368dfa25f.jpg'}, {'id': 3412534, 'image': 'https://media.rawg.io/media/screenshots/585/585fd40ad660779a79e2853f3cd7a833.jpg'}, {'id': 3412535, 'image': 'https://media.rawg.io/media/screenshots/7cb/7cb256eecd9dd0bb54d4524dc2a9b7ee.jpg'}], 'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}}, {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}}], 'genres': [{'id': 2, 'name': 'Shooter', 'slug': 'shooter'}, {'id': 3, 'name': 'Adventure', 'slug': 'adventure'}, {'id': 4, 'name': 'Action', 'slug': 'action'}]}], 'user_platforms': False}
🔎 Buscando: Hollow Knight
🛰 Status: 200